ALTER TABLE project ADD "domain" VARCHAR(50);

UPDATE project SET "domain" ='Application Software' WHERE
url='https://github.com/borgbackup/borg' OR	
url='https://github.com/qbittorrent/qBittorrent' OR	
url='https://github.com/darktable-org/darktable' OR	
url='https://github.com/openwall/john' OR	
url='https://github.com/libretro/RetroArch' OR	
url='https://github.com/tmux/tmux' OR	
url='https://github.com/duplicati/duplicati' OR	
url='https://github.com/jellyfin/jellyfin' OR	
url='https://github.com/dbeaver/dbeaver' OR	
url='https://github.com/adobe/brackets' OR	
url='https://github.com/atom/atom' OR	
url='https://github.com/ppy/osu' OR	
url='https://github.com/bolt/bolt' OR	
url='https://github.com/joomla/joomla-cms' OR	
url='https://github.com/laravel/laravel' OR	
url='https://github.com/fastlane/fastlane' OR	
url='https://github.com/spree/spree' OR	
url='https://github.com/jekyll/jekyll';	

UPDATE project SET "domain" ='Libraries and back-End Frameworks' WHERE
url='https://github.com/libgit2/libgit2' OR	
url='https://github.com/reactiveui/ReactiveUI' OR	
url='https://github.com/hashicorp/vagrant' OR	
url='https://github.com/electron/electron' OR	
url='https://github.com/protocolbuffers/protobuf' OR	
url='https://github.com/swoole/swoole-src' OR	
url='https://github.com/tensorflow/tensorflow' OR	
url='https://github.com/BVLC/caffe' OR	
url='https://github.com/ReactiveX/RxJava' OR	
url='https://github.com/eclipse-vertx/vert.x' OR	
url='https://github.com/libgdx/libgdx' OR	
url='https://github.com/dotnet/efcore' OR	
url='https://github.com/serverless/serverless' OR	
url='https://github.com/symfony/console' OR	
url='https://github.com/phalcon/cphalcon' OR	
url='https://github.com/sebastianbergmann/phpunit' OR	
url='https://github.com/yiisoft/yii2' OR	
url='https://github.com/kivy/kivy' OR	
url='https://github.com/pandas-dev/pandas' OR	
url='https://github.com/Pylons/pyramid' OR	
url='https://github.com/scikit-learn/scikit-learn' OR	
url='https://github.com/explosion/spaCy' OR	
url='https://github.com/fog/fog';

UPDATE project SET "domain" ='Software Tools' WHERE
url='https://github.com/mruby/mruby' OR	
url='https://github.com/OpenRA/OpenRA' OR	
url='https://github.com/apache/druid' OR	
url='https://github.com/oracle/graal' OR	
url='https://github.com/babel/babel' OR	
url='https://github.com/TryGhost/Ghost' OR	
url='https://github.com/meteor/meteor' OR	
url='https://github.com/pinpoint-apm/pinpoint' OR	
url='https://github.com/emscripten-core/emscripten' OR	
url='https://github.com/microsoft/PTVS' OR	
url='https://github.com/sveltejs/svelte' OR	
url='https://github.com/composer/composer' OR	
url='https://github.com/ipython/ipython' OR	
url='https://github.com/getsentry/sentry' OR	
url='https://github.com/Homebrew/brew' OR	
url='https://github.com/chef/chef' OR	
url='https://github.com/cucumber/cucumber-ruby';

UPDATE project SET "domain" ='System Software' WHERE
url='https://github.com/qemu/qemu' OR
url='https://github.com/redis/redis' OR
url='https://github.com/EventStore/EventStore' OR
url='https://github.com/apple/foundationdb' OR
url='https://github.com/mongodb/mongo' OR
url='https://github.com/jenkinsci/jenkins' OR
url='https://github.com/realm/realm-java' OR
url='https://github.com/elastic/elasticsearch' OR
url='https://github.com/systemd/systemd' OR
url='https://github.com/ansible/ansible' OR
url='https://github.com/directus/v8-archive' OR
url='https://github.com/certbot/certbot' OR
url='https://github.com/diaspora/diaspora' OR
url='https://github.com/puppetlabs/puppet';

UPDATE project SET "domain" ='Front-End Frameworks' WHERE
url='https://github.com/abpframework/abp' OR	
url='https://github.com/AvaloniaUI/Avalonia' OR	
url='https://github.com/twbs/bootstrap' OR	
url='https://github.com/facebook/react' OR	
url='https://github.com/webpack/webpack' OR	
url='https://github.com/timber/timber' OR	
url='https://github.com/bokeh/bokeh';

UPDATE project SET "domain" ='Documentation' WHERE
url='https://github.com/OpenGenus/cosmos';