package br.ufjf.dcc.jasome.jdbc.dao;

import br.ufjf.dcc.gmr.core.jasome.model.Login;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;

/**
 *
 * @author Beatr
 */
public class LoginDao {
    
    private final Connection connection;

    public LoginDao(Connection connection) {
        this.connection = connection;
    }
    
    public int insert(Login login) throws SQLException {

        String sql = "INSERT INTO tb_login "
                + "(login,pass,type) "
                + "VALUES (?,?,?) "
                + "RETURNING id;";

        PreparedStatement stmt = null;

        ResultSet tableKeys = null;

        try {
            stmt = connection.prepareStatement(sql);
            //set value
            stmt.setString(1, login.getUser());
            stmt.setString(2, login.getPass());
            stmt.setString(3, login.getType());
            tableKeys = stmt.executeQuery();
            tableKeys.next();

            int autoGeneratedID = tableKeys.getInt(1);

            return autoGeneratedID;

        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }
    
    public List<Login> select() throws SQLException {
        List<Login> listLogin = new ArrayList<>();
        Login login = new Login();

        String sql = "SELECT * FROM tb_login ";

        ResultSet resultSet = null;

        PreparedStatement stmt = null;
        try {
            stmt = connection.prepareStatement(sql);
            resultSet = stmt.executeQuery();
            while (resultSet.next()) {
                login = new Login();
                int id = resultSet.getInt("id");
                String user = resultSet.getString("user");
                String pass = resultSet.getString("pass");
                String type = resultSet.getString("type");
                login.setId(id);
                login.setUser(user);
                login.setPass(pass);
                login.setType(type);
                listLogin.add(login);
            }
            return listLogin;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public Login selectID(int id) throws SQLException {
        Login login = new Login();

        String sql = "SELECT * FROM tb_login WHERE id = " + id;

        PreparedStatement stmt = null;

        ResultSet resultSet = null;

        try {
            stmt = connection.prepareStatement(sql);
            resultSet = stmt.executeQuery();
            resultSet.next();

            int loginId = resultSet.getInt("id");
            String user = resultSet.getString("user");
            String pass = resultSet.getString("pass");
            String type = resultSet.getString("type");
            login.setId(id);
            login.setUser(user);
            login.setPass(pass);
            login.setType(type);
            return login;

        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }
    
    public List<String> isUserRegistered() throws SQLException {
        List<String> users = new ArrayList<>();
        String sql = "SELECT * FROM tb_login";

        ResultSet resultSet = null;

        PreparedStatement stmt = null;
        try {
            stmt = connection.prepareStatement(sql);
            resultSet = stmt.executeQuery();
            while (resultSet.next()) {
                String user = resultSet.getString("login");
                users.add(user);
            }
            return users;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }
    
    public int getUserId(String user) throws SQLException {
        int id = -1;
        String sql = "SELECT id FROM tb_login where login='"+user+"'";
        ResultSet resultSet = null;

        PreparedStatement stmt = null;
        try {
            stmt = connection.prepareStatement(sql);
            resultSet = stmt.executeQuery();
            while (resultSet.next()) {
                id = resultSet.getInt("id");
            }
            return id;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }
    
    public boolean enterSystem(String user, String pass) throws SQLException {
        String sql = "SELECT login, pass FROM tb_login where login='"+user+"'";
        ResultSet resultSet = null;
        String login = "";
        String password = "";
        PreparedStatement stmt = null;
        try {
            stmt = connection.prepareStatement(sql);
            resultSet = stmt.executeQuery();
            while (resultSet.next()) {
                login = resultSet.getString("login");
                password = resultSet.getString("pass");
                if(user.equals(login) && password.equals(pass)){
                    return true;
                }
            }
            return false;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }
}
