/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufjf.dcc.jasome.jdbc.dao;

import br.ufjf.dcc.gmr.core.db.ConnectionFactory;
import br.ufjf.dcc.gmr.core.jasome.model.MethodMetrics;
import br.ufjf.dcc.gmr.core.jasome.model.Metric;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author anton
 */
public class MethodMetricsDao {

    private Connection connection;
    List<MethodMetrics> listMethodMetrics;
    MethodMetrics methodMetrics;
    ResultSet tableKeys;

    public MethodMetricsDao() {
        this.connection = ConnectionFactory.getConnection();
        listMethodMetrics = new ArrayList<>();
    }

    public int insert(MethodMetrics methodMetrics) {
        String sql = "INSERT INTO tb_methodMetrics "
                + "(ciID,diID,finID,foutID,iovarsID,mclcID,nbdID,ncompID,nopID,nvarID,siID,tlocID,vgID,classID)"
                + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) "
                + "RETURNING id;";

        PreparedStatement stmt = null;
        ResultSet tableKeys = null;

        try {
            stmt = connection.prepareStatement(sql);

            stmt.setInt(1, methodMetrics.getCi().getId());
            stmt.setInt(2, methodMetrics.getDi().getId());
            stmt.setInt(3, methodMetrics.getFin().getId());
            stmt.setInt(4, methodMetrics.getFout().getId());
            stmt.setInt(5, methodMetrics.getIovars().getId());
            stmt.setInt(6, methodMetrics.getMclc().getId());
            stmt.setInt(7, methodMetrics.getNbd().getId());
            stmt.setInt(8, methodMetrics.getNcomp().getId());
            stmt.setInt(9, methodMetrics.getNop().getId());
            stmt.setInt(10, methodMetrics.getNvar().getId());
            stmt.setInt(11, methodMetrics.getSi().getId());
            stmt.setInt(12, methodMetrics.getTloc().getId());
            stmt.setInt(13, methodMetrics.getVg().getId());
            stmt.setInt(14, methodMetrics.getClassId());

            tableKeys = stmt.executeQuery();
            tableKeys.next();
            int autoGeneratedID = tableKeys.getInt(1);
            stmt.close();
            return autoGeneratedID;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public List<MethodMetrics> select() {
        String sql = "SELECT * FROM tb_methodMetrics";

        MethodMetrics methodMetrics = null;
        List<MethodMetrics> listMethodMetrics = new ArrayList<>();
        MetricDao metricDao = new MetricDao();
        PreparedStatement stmt = null;

        ResultSet resultSet = null;
        try {
            stmt = connection.prepareStatement(sql);
            resultSet = stmt.executeQuery();
            while (resultSet.next()) {

                methodMetrics = new MethodMetrics();

                int ciID = resultSet.getInt("ciID");
                int diID = resultSet.getInt("diID");
                int finID = resultSet.getInt("finID");
                int foutID = resultSet.getInt("foutID");
                int iovarsID = resultSet.getInt("iovarsID");
                int mclcID = resultSet.getInt("mclcID");
                int nbdID = resultSet.getInt("nbdID");
                int ncompID = resultSet.getInt("ncompID");
                int nopID = resultSet.getInt("nopID");
                int nvarID = resultSet.getInt("nvarID");
                int siID = resultSet.getInt("siID");
                int tlocID = resultSet.getInt("tlocID");
                int vgID = resultSet.getInt("vgID");

                Metric ciIDMetric = metricDao.selectID(ciID);
                Metric diIDMetric = metricDao.selectID(diID);
                Metric finIDMetric = metricDao.selectID(finID);
                Metric foutIDMetric = metricDao.selectID(foutID);
                Metric iovarsIDMetric = metricDao.selectID(iovarsID);
                Metric mclcIDMetric = metricDao.selectID(mclcID);
                Metric nbdIDMetric = metricDao.selectID(nbdID);
                Metric ncompIDMetric = metricDao.selectID(ncompID);
                Metric nopIDMetric = metricDao.selectID(nopID);
                Metric nvarIDMetric = metricDao.selectID(nvarID);
                Metric siIDMetric = metricDao.selectID(siID);
                Metric tlocIDMetric = metricDao.selectID(tlocID);
                Metric vgIDMetric = metricDao.selectID(vgID);

                methodMetrics.setCi(ciIDMetric);
                methodMetrics.setDi(diIDMetric);
                methodMetrics.setFin(finIDMetric);
                methodMetrics.setFout(foutIDMetric);
                methodMetrics.setIovars(iovarsIDMetric);
                methodMetrics.setMclc(mclcIDMetric);
                methodMetrics.setNbd(nbdIDMetric);
                methodMetrics.setNcomp(ncompIDMetric);
                methodMetrics.setNop(nopIDMetric);
                methodMetrics.setNvar(nvarIDMetric);
                methodMetrics.setSi(siIDMetric);
                methodMetrics.setTloc(tlocIDMetric);
                methodMetrics.setVg(vgIDMetric);

                methodMetrics.setId(resultSet.getInt("id"));

            }
            listMethodMetrics.add(methodMetrics);
            stmt.close();
            return listMethodMetrics;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

    public MethodMetrics selectID(int id) throws SQLException {
        MetricDao metricDao = new MetricDao();
        MethodMetrics methodMetrics = null;
        String sql = "SELECT * FROM tb_methodMetrics WHERE ID = " + id;

        PreparedStatement stmt = null;

        ResultSet resultSet = null;

        try {
            stmt = connection.prepareStatement(sql);
            resultSet = stmt.executeQuery();
            resultSet.next();
            methodMetrics = new MethodMetrics();

            int ciID = resultSet.getInt("ciID");
            int diID = resultSet.getInt("diID");
            int finID = resultSet.getInt("finID");
            int foutID = resultSet.getInt("foutID");
            int iovarsID = resultSet.getInt("iovarsID");
            int mclcID = resultSet.getInt("mclcID");
            int nbdID = resultSet.getInt("nbdID");
            int ncompID = resultSet.getInt("ncompID");
            int nopID = resultSet.getInt("nopID");
            int nvarID = resultSet.getInt("nvarID");
            int siID = resultSet.getInt("siID");
            int tlocID = resultSet.getInt("tlocID");
            int vgID = resultSet.getInt("vgID");

            methodMetrics.setCi(metricDao.selectID(ciID));
            methodMetrics.setDi(metricDao.selectID(diID));
            methodMetrics.setFin(metricDao.selectID(finID));
            methodMetrics.setFout(metricDao.selectID(foutID));
            methodMetrics.setIovars(metricDao.selectID(iovarsID));
            methodMetrics.setMclc(metricDao.selectID(mclcID));
            methodMetrics.setNbd(metricDao.selectID(nbdID));
            methodMetrics.setNcomp(metricDao.selectID(ncompID));
            methodMetrics.setNop(metricDao.selectID(nopID));
            methodMetrics.setNvar(metricDao.selectID(nvarID));
            methodMetrics.setSi(metricDao.selectID(siID));
            methodMetrics.setTloc(metricDao.selectID(tlocID));
            methodMetrics.setVg(metricDao.selectID(vgID));

            int methodId = resultSet.getInt("id");
            methodMetrics.setId(methodId);

            return methodMetrics;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void delete(int id) {
        String sql = "DELETE FROM tb_methodMetrics WHERE id = ? ";

        try {
            PreparedStatement stmt = connection.prepareStatement(sql);
            //set values
            stmt.setInt(1, id);
            stmt.executeUpdate();
            stmt.close();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void update(MethodMetrics methodMetric, int id) {
        String sql =null; // "UPDATE tb_metric SET name = '" + metric.getName() + "', description = '" + metric.getDescription() + "', value = '" + metric.getValue() + "' WHERE ID = '" + id + "';";
        try {
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.executeUpdate();
            stmt.close();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
