/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufjf.dcc.jasome.jdbc.dao;

import br.ufjf.dcc.gmr.core.db.ConnectionFactory;
import br.ufjf.dcc.gmr.core.jasome.model.Metric;
import br.ufjf.dcc.gmr.core.jasome.model.PackageMetrics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author anton
 */
public class MetricDao {

    private Connection connection;

    public MetricDao() {
        this.connection = ConnectionFactory.getConnection();

    }

    public int insert(Metric metric) throws SQLException {

        String sql = "INSERT INTO tb_metric "
                + "(name, description, value)"
                + "VALUES (?,?,?);";
        
        PreparedStatement stmt = null;
        
        ResultSet tableKeys = null;
        
        try {
            stmt = connection.prepareStatement(sql);

            stmt.setString(1, metric.getName());
            stmt.setString(2, metric.getDescription());
            stmt.setDouble(3, metric.getValue());

            tableKeys = stmt.executeQuery();

            tableKeys.next();
            int autoGeneratedID = tableKeys.getInt("id");

            return autoGeneratedID;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }
    
    public void delete(int id) throws SQLException {
        String sql = "DELETE FROM tb_metric WHERE ID = ?";
        
        PreparedStatement stmt = null;
                
        try {
            stmt = connection.prepareStatement(sql);
            //set values
            stmt.setInt(1, id);
            stmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public List<Metric> select() throws SQLException {
        Metric metric;
        metric = new Metric();
        List<Metric> listMetrics = new ArrayList<>();
       
        PreparedStatement stmt = null;
        
        String sql = "SELECT * FROM tb_metric";
        
        ResultSet tableKeys;

        try {
            stmt = connection.prepareStatement(sql);
            tableKeys = stmt.executeQuery();
            //tableKeys = stmt.getGeneratedKeys();
            while (tableKeys.next()) {
                metric.setId(tableKeys.getInt(1));
                metric.setName(tableKeys.getString("name"));
                metric.setDescription(tableKeys.getString("description"));
                metric.setValue(tableKeys.getDouble("value"));
                listMetrics.add(metric);
            }
            return listMetrics;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public Metric selectID(int id) throws SQLException {
        Metric metric;
        metric = new Metric();

        String sql = "SELECT * FROM tb_metric WHERE ID = " + id;
        
        PreparedStatement stmt = null;
        
        ResultSet tableKeys;
        
        try {
            stmt = connection.prepareStatement(sql);
            tableKeys = stmt.executeQuery();
            //tableKeys = stmt.getGeneratedKeys();
            tableKeys.next();
            metric.setId(tableKeys.getInt(1));
            metric.setName(tableKeys.getString("name"));
            metric.setDescription(tableKeys.getString("description"));
            metric.setValue(tableKeys.getDouble("value"));
            return metric;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }
}
