/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufjf.dcc.jasome.jdbc.dao;

import br.ufjf.dcc.gmr.core.db.ConnectionFactory;
import br.ufjf.dcc.gmr.core.jasome.model.Metric;
import br.ufjf.dcc.gmr.core.jasome.model.PackageMetrics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;

/**
 *
 * @author anton
 */
public class PackageMetricsDao {

    private final Connection connection;

    public PackageMetricsDao(Connection connection) {
        this.connection = connection;
    }

    public int insert(PackageMetrics packageMetrics) throws SQLException {

        String sql = "INSERT INTO tb_packageMetrics "
                + "(aID,ccrcID,caID,ceID,dmsId,iId,nocID,noiID,pkgRCiID,pkgTCiID,tlocID,packageName) " //adicionar dmsId, iId
                + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?) " //adicionar ?,?
                + "RETURNING id;";

        PreparedStatement stmt = null;

        ResultSet tableKeys = null;

        try {
            stmt = connection.prepareStatement(sql);
                       
            if (packageMetrics.getA() == null) {
                stmt.setNull(1, java.sql.Types.INTEGER);
            } else {
                stmt.setInt(1, packageMetrics.getA().getId());
            }
            if (packageMetrics.getCcrc() == null) {
                stmt.setNull(2, java.sql.Types.INTEGER);
            } else {
                stmt.setInt(2, packageMetrics.getCcrc().getId());
            }
            if (packageMetrics.getCa() == null) {
                stmt.setNull(3, java.sql.Types.INTEGER);
            } else {
                stmt.setInt(3, packageMetrics.getCa().getId());
            }
            if (packageMetrics.getCe() == null) {
                stmt.setNull(4, java.sql.Types.INTEGER);
            } else {
                stmt.setInt(4, packageMetrics.getCe().getId());
            }
            if (packageMetrics.getDms() == null) {
                stmt.setNull(5, java.sql.Types.INTEGER);
            } else {
                stmt.setInt(5, packageMetrics.getDms().getId());
            }
            if (packageMetrics.getI() == null) {
                stmt.setNull(6, java.sql.Types.INTEGER);
            } else {
                stmt.setInt(6, packageMetrics.getI().getId());
            }
            if (packageMetrics.getNoc() == null) {
                stmt.setNull(7, java.sql.Types.INTEGER);
            } else {
                stmt.setInt(7, packageMetrics.getNoc().getId());
            }
            if (packageMetrics.getNoi() == null) {
                stmt.setNull(8, java.sql.Types.INTEGER);
            } else {
                stmt.setInt(8, packageMetrics.getNoi().getId());
            }
            if (packageMetrics.getPkgRCi() == null) {
                stmt.setNull(9, java.sql.Types.INTEGER);
            } else {
                stmt.setInt(9, packageMetrics.getPkgRCi().getId());
            }
            if (packageMetrics.getPkgTCi() == null) {
                stmt.setNull(10, java.sql.Types.INTEGER);
            } else {
                stmt.setInt(10, packageMetrics.getPkgTCi().getId());
            }
            if (packageMetrics.getTloc() == null) {
                stmt.setNull(11, java.sql.Types.INTEGER);
            } else {
                stmt.setInt(11, packageMetrics.getTloc().getId());
            }
            
            stmt.setString(12, packageMetrics.getName());
            //  stmt.setInt(12, packageMetrics.getVersionId());

            tableKeys = stmt.executeQuery();
            //tableKeys = stmt.getGeneratedKeys();
            tableKeys.next();
            int autoGeneratedID = tableKeys.getInt(1);
            return autoGeneratedID;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public void delete(int id) throws SQLException {
        String sql = "DELETE FROM tb_packageMetrics WHERE ID = ?";

        PreparedStatement stmt = null;

        try {
            stmt = connection.prepareStatement(sql);
            //set values
            stmt.setInt(1, id);
            stmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public List<PackageMetrics> select() throws SQLException {
        MetricDao metrics = new MetricDao(connection);
        List<PackageMetrics> listPackageMetrics = new ArrayList<>();
        PackageMetrics packageMetrics = null;

        String sql = "SELECT * FROM tb_packageMetrics";

        PreparedStatement stmt = null;

        ResultSet resultSet = null;

        try {
            stmt = connection.prepareStatement(sql);
            //set values
            //stmt.setInt(1, projectMetrics.getId());
            //stmt.setString(2, projectMetrics.getSourceDir());
            resultSet = stmt.executeQuery();
            //tableKeys = stmt.getGeneratedKeys();
            while (resultSet.next()) {

                packageMetrics = new PackageMetrics();

                packageMetrics.setA(insert(resultSet, metrics, "aID"));
                packageMetrics.setCcrc(insert(resultSet, metrics, "ccrcID"));
                packageMetrics.setCa(insert(resultSet, metrics, "caID"));
                packageMetrics.setCe(insert(resultSet, metrics, "ceID"));
                packageMetrics.setDms(insert(resultSet, metrics, "dmsID"));
                packageMetrics.setI(insert(resultSet, metrics, "iID"));
                packageMetrics.setNoc(insert(resultSet, metrics, "nocID"));
                packageMetrics.setNoi(insert(resultSet, metrics, "noiID"));
                packageMetrics.setPkgRCi(insert(resultSet, metrics, "pkgRCiID"));
                packageMetrics.setPkgTCi(insert(resultSet, metrics, "pkgTCiID"));
                packageMetrics.setTloc(insert(resultSet, metrics, "tlocID"));

                int packageId = resultSet.getInt("id");
                packageMetrics.setId(packageId);

                listPackageMetrics.add(packageMetrics);
            }

            return listPackageMetrics;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public PackageMetrics selectID(int id) throws SQLException {
        MetricDao metrics = new MetricDao(connection);
        PackageMetrics packageMetrics = null;

        String sql = "SELECT * FROM tb_packageMetrics WHERE ID = " + id;

        PreparedStatement stmt = null;

        ResultSet resultSet = null;

        try {
            stmt = connection.prepareStatement(sql);
            resultSet = stmt.executeQuery();

            //tableKeys = stmt.getGeneratedKeys();
            resultSet.next();

            packageMetrics = new PackageMetrics();

            packageMetrics.setA(insert(resultSet, metrics, "aID"));
            packageMetrics.setCcrc(insert(resultSet, metrics, "ccrcID"));
            packageMetrics.setCa(insert(resultSet, metrics, "caID"));
            packageMetrics.setCe(insert(resultSet, metrics, "ceID"));
            packageMetrics.setDms(insert(resultSet, metrics, "dmsID"));
            packageMetrics.setI(insert(resultSet, metrics, "iID"));
            packageMetrics.setNoc(insert(resultSet, metrics, "nocID"));
            packageMetrics.setNoi(insert(resultSet, metrics, "noiID"));
            packageMetrics.setPkgRCi(insert(resultSet, metrics, "pkgRCiID"));
            packageMetrics.setPkgTCi(insert(resultSet, metrics, "pkgTCiID"));
            packageMetrics.setTloc(insert(resultSet, metrics, "tlocID"));

            int packageId = resultSet.getInt("id");
            packageMetrics.setId(packageId);

            return packageMetrics;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public Metric insert(ResultSet resultSet, MetricDao metricDao, String name) throws SQLException {

        if (resultSet.getInt(name) == 0) {
            return null;
        } else {
            int ID = resultSet.getInt(name);
            Metric metric = metricDao.selectID(ID);
            return metric;
        }
    }

    public void update(PackageMetrics packageMetrics, int id) throws SQLException {
        String sql = null; // "UPDATE tb_packageMetrics SET '" + metric.getName() + " = '" + metric.getValue() + "' WHERE ID = '" + id + "'";

        PreparedStatement stmt = null;

        try {
            stmt = connection.prepareStatement(sql);
            stmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);

        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public void updateVersionId(PackageMetrics packageMetric) throws SQLException {
        String sql = "UPDATE tb_packageMetrics SET versionID = ? WHERE ID = ? ;";
        System.out.println(sql);

        PreparedStatement stmt = null;
        try {
            stmt = connection.prepareStatement(sql);
            stmt.setInt(1, packageMetric.getVersionId());
            stmt.setInt(2, packageMetric.getId());
            stmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }
}
