/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufjf.dcc.jasome.jdbc.dao;

import br.ufjf.dcc.gmr.core.db.ConnectionFactory;
import br.ufjf.dcc.gmr.core.jasome.model.Metric;
import br.ufjf.dcc.gmr.core.jasome.model.VersionMetrics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;

/**
 *
 * @author anton
 */
public class VersionMetricsDao {

    private final Connection connection;

    public VersionMetricsDao() {
        this.connection = ConnectionFactory.getConnection();
    }

    public int insert(VersionMetrics versionMetrics) throws SQLException {
        String sql = "INSERT INTO tb_versionmetrics "
                + "(tloc) "
                + "VALUES (?) "
                + "RETURNING id;";

        PreparedStatement stmt = null;

        ResultSet tableKeys = null;

        try {
            stmt = connection.prepareStatement(sql);
            //set values
            stmt.setInt(1, versionMetrics.getTloc().getId());
            tableKeys = stmt.executeQuery();
            //tableKeys = stmt.getGeneratedKeys();
            tableKeys.next();
            int autoGeneratedID = tableKeys.getInt(1);
            return autoGeneratedID;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public void delete(int id) throws SQLException {
        String sql = "DELETE FROM tb_versionmetrics WHERE ID = ?";

        PreparedStatement stmt = null;

        try {
            stmt = connection.prepareStatement(sql);
            //set values
            stmt.setInt(1, id);
            stmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public List<VersionMetrics> select(int id) throws SQLException {
        VersionMetrics versionMetrics = new VersionMetrics();
        List<VersionMetrics> listVersionMetrics = new ArrayList<>();
        MetricDao metrics = new MetricDao();

        String sql = "SELECT * FROM tb_versionmetrics ";

        PreparedStatement stmt = null;

        ResultSet tableKeys = null;

        try {
            stmt = connection.prepareStatement(sql);
            //set values
            //stmt.setInt(1, projectMetrics.getId());
            //stmt.setString(2, projectMetrics.getSourceDir());
            tableKeys = stmt.executeQuery();
            //tableKeys = stmt.getGeneratedKeys()
            while (tableKeys.next()) {

                int tlocID = tableKeys.getInt("tloc");

                versionMetrics.getTloc().setId(tlocID);

                int versionId = tableKeys.getInt(1);

                versionMetrics.setId(versionId);

                versionMetrics.setTloc(metrics.selectID(versionMetrics.getTloc().getId()));

                listVersionMetrics.add(versionMetrics);
            }
            return listVersionMetrics;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public VersionMetrics selectID(int id) throws SQLException {
        VersionMetrics versionMetrics;
        versionMetrics = new VersionMetrics();
        MetricDao metrics = new MetricDao();

        String sql = "SELECT * FROM tb_versionmetrics WHERE ID = " + id;

        PreparedStatement stmt = null;

        ResultSet tableKeys = null;

        try {
            stmt = connection.prepareStatement(sql);
            tableKeys = stmt.executeQuery();
            //tableKeys = stmt.getGeneratedKeys();
            tableKeys.next();

            int tlocID = tableKeys.getInt("tloc");

            versionMetrics.getTloc().setId(tlocID);

            versionMetrics.setTloc(metrics.selectID(versionMetrics.getTloc().getId()));

            return versionMetrics;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }

    public void update(Metric metric, String id) throws SQLException {
        String sql = "UPDATE tb_versionMetrics SET tloc = '" + metric.getValue() + "' WHERE ID = '" + id + "'";

        PreparedStatement stmt = null;

        try {
            stmt = connection.prepareStatement(sql);
            stmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }
    }
}
