/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufjf.dcc.jasome.jdbc.dao;

import br.ufjf.dcc.gmr.core.jasome.model.MethodMetrics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author anton
 */
public class MethodMetricsDao {
    private Connection connection;
    List<MethodMetrics> listMethodMetrics;
    MethodMetrics methodMetrics;
    ResultSet tableKeys;
    
    public int insert(MethodMetrics methodMetrics){
        String sql = "INSERT INTO tb_methodMetrics "
                + "(ci,di,fin,fout,iovars,mclc,nbd,ncomp,nop,nvar,si,tloc,vg)"
                + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?);";
        try {
            PreparedStatement stmt = connection.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);
            stmt.setInt(1, methodMetrics.getCi().getId());
            stmt.setInt(1, methodMetrics.getDi().getId());
            stmt.setInt(1, methodMetrics.getFin().getId());
            stmt.setInt(1, methodMetrics.getFout().getId());
            stmt.setInt(1, methodMetrics.getIovars().getId());
            stmt.setInt(1, methodMetrics.getMclc().getId());
            stmt.setInt(1, methodMetrics.getNbd().getId());
            stmt.setInt(1, methodMetrics.getNcomp().getId());
            stmt.setInt(1, methodMetrics.getNop().getId());
            stmt.setInt(1, methodMetrics.getNvar().getId());
            stmt.setInt(1, methodMetrics.getSi().getId());
            stmt.setInt(1, methodMetrics.getTloc().getId());
            stmt.setInt(1, methodMetrics.getVg().getId());
            stmt.executeUpdate();
            tableKeys = stmt.getGeneratedKeys();
            tableKeys.next();
            int autoGeneratedID = tableKeys.getInt(1);
            stmt.close();
            return autoGeneratedID;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
    
    public List<MethodMetrics> select(){
        return null;
    }
    
    public void delete(int id){
        String sql = "DELETE FROM tb_methodMetrics WHERE id = ? ";
        
        try {
            PreparedStatement stmt = connection.prepareStatement(sql);
            //set values
            stmt.setInt(1, id);
            stmt.executeUpdate();
            stmt.close();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
    
}
