DROP TABLE tb_methodMetrics;
DROP TABLE tb_classMetrics;
DROP TABLE tb_packageMetrics;
DROP TABLE tb_versionMetrics;
DROP TABLE tb_projectMetrics;
DROP TABLE tb_metric;


CREATE TABLE tb_metric (
    ID serial NOT NULL,
    description varchar(255) NOT NULL,
    name varchar(255),
    value REAL,
    PRIMARY KEY (ID)
);

CREATE TABLE tb_projectMetrics(
    ID serial NOT NULL,
    sourceDir varchar(256) NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE tb_versionMetrics (
    ID serial NOT NULL,
    tlocID serial NOT NULL,
    projectID serial NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (tlocID) REFERENCES tb_metric(ID),
    FOREIGN KEY (projectID) REFERENCES tb_projectMetrics(ID)
);


CREATE TABLE tb_packageMetrics (
    ID serial NOT NULL,
    aID serial NOT NULL,
    ccrcID serial NOT NULL,
    caID serial NOT NULL,
    ceID serial NOT NULL,
    dmsID serial NOT NULL,
    iID serial NOT NULL,
    nocID serial NOT NULL,
    noiID serial NOT NULL,
    pkgRCiD serial NOT NULL,
    pkgTCiID serial NOT NULL,
    tlocID serial NOT NULL,
    versionID serial NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (aID) REFERENCES tb_metric(ID),
    FOREIGN KEY (ccrcID) REFERENCES tb_metric(ID),
    FOREIGN KEY (caID) REFERENCES tb_metric(ID),
    FOREIGN KEY (ceID) REFERENCES tb_metric(ID),
    FOREIGN KEY (dmsID) REFERENCES tb_metric(ID),
    FOREIGN KEY (iID) REFERENCES tb_metric(ID),
    FOREIGN KEY (nocID) REFERENCES tb_metric(ID),
    FOREIGN KEY (noiID) REFERENCES tb_metric(ID),
    FOREIGN KEY (pkgRCiD) REFERENCES tb_metric(ID),
    FOREIGN KEY (pkgTCiID) REFERENCES tb_metric(ID),
    FOREIGN KEY (tlocID) REFERENCES tb_metric(ID),
    FOREIGN KEY (versionID) REFERENCES tb_versionMetrics(ID)
);


CREATE TABLE tb_classMetrics (
    ID serial NOT NULL,
    aa serial NOT NULL,
    ad serial NOT NULL,
    ai serial NOT NULL,
    ait serial NOT NULL,
    ao serial NOT NULL,
    av serial NOT NULL,
    clrci serial NOT NULL,
    cltci serial NOT NULL,
    dit serial NOT NULL,
    hmd serial NOT NULL,
    hmi serial NOT NULL,
    mhf serial NOT NULL,
    mif serial NOT NULL,
    ma serial NOT NULL,
    md serial NOT NULL,
    mi serial NOT NULL,
    mit serial NOT NULL,
    mo serial NOT NULL,
    nf serial NOT NULL,
    nm serial NOT NULL,
    nma serial NOT NULL,
    nmi serial NOT NULL,
    noa serial NOT NULL,
    noch serial NOT NULL,
    nod serial NOT NULL,
    nol serial NOT NULL,
    nopa serial NOT NULL,
    norm serial NOT NULL,
    npf serial NOT NULL,
    npm serial NOT NULL,
    nsf serial NOT NULL,
    nsm serial NOT NULL,
    pmr serial NOT NULL,
    pmd serial NOT NULL,
    pmi serial NOT NULL,
    rtloc serial NOT NULL,
    six serial NOT NULL,
    tloc serial NOT NULL,
    wmc serial NOT NULL,
    packageID serial NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (aa) REFERENCES tb_metric(ID),
    FOREIGN KEY (ad) REFERENCES tb_metric(ID),
    FOREIGN KEY (ai) REFERENCES tb_metric(ID),
    FOREIGN KEY (ait) REFERENCES tb_metric(ID),
    FOREIGN KEY (ao) REFERENCES tb_metric(ID),
    FOREIGN KEY (av) REFERENCES tb_metric(ID),
    FOREIGN KEY (clrci) REFERENCES tb_metric(ID),
    FOREIGN KEY (cltci) REFERENCES tb_metric(ID),
    FOREIGN KEY (dit) REFERENCES tb_metric(ID),
    FOREIGN KEY (hmd) REFERENCES tb_metric(ID),
    FOREIGN KEY (hmi) REFERENCES tb_metric(ID),
    FOREIGN KEY (mhf) REFERENCES tb_metric(ID),
    FOREIGN KEY (mif) REFERENCES tb_metric(ID),
    FOREIGN KEY (ma) REFERENCES tb_metric(ID),
    FOREIGN KEY (md) REFERENCES tb_metric(ID),
    FOREIGN KEY (mi) REFERENCES tb_metric(ID),
    FOREIGN KEY (mit) REFERENCES tb_metric(ID),
    FOREIGN KEY (mo) REFERENCES tb_metric(ID),
    FOREIGN KEY (nf) REFERENCES tb_metric(ID),
    FOREIGN KEY (nm) REFERENCES tb_metric(ID),
    FOREIGN KEY (nma) REFERENCES tb_metric(ID),
    FOREIGN KEY (nmi) REFERENCES tb_metric(ID),
    FOREIGN KEY (noa) REFERENCES tb_metric(ID),
    FOREIGN KEY (noch) REFERENCES tb_metric(ID),
    FOREIGN KEY (nod) REFERENCES tb_metric(ID),
    FOREIGN KEY (nol) REFERENCES tb_metric(ID),
    FOREIGN KEY (nopa) REFERENCES tb_metric(ID),
    FOREIGN KEY (norm) REFERENCES tb_metric(ID),
    FOREIGN KEY (npf) REFERENCES tb_metric(ID),
    FOREIGN KEY (npm) REFERENCES tb_metric(ID),
    FOREIGN KEY (nsf) REFERENCES tb_metric(ID),
    FOREIGN KEY (nsm) REFERENCES tb_metric(ID),
    FOREIGN KEY (pmr) REFERENCES tb_metric(ID),
    FOREIGN KEY (pmd) REFERENCES tb_metric(ID),
    FOREIGN KEY (pmi) REFERENCES tb_metric(ID),
    FOREIGN KEY (rtloc) REFERENCES tb_metric(ID),
    FOREIGN KEY (six) REFERENCES tb_metric(ID),
    FOREIGN KEY (tloc) REFERENCES tb_metric(ID),
    FOREIGN KEY (wmc) REFERENCES tb_metric(ID),
    FOREIGN KEY (packageID) REFERENCES tb_packageMetrics(ID)
);

CREATE TABLE tb_methodMetrics (
    ID serial NOT NULL,
    ci serial NOT NULL,
    di serial NOT NULL,
    fin serial NOT NULL,
    fout serial NOT NULL,
    iovars serial NOT NULL,
    mclc serial NOT NULL,
    nbd serial NOT NULL,
    ncomp serial NOT NULL,
    nop serial NOT NULL,
    nvar serial NOT NULL,
    si serial NOT NULL,
    tloc serial NOT NULL,
    vg serial NOT NULL,
    classID serial NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ci) REFERENCES tb_metric(ID),
    FOREIGN KEY (di) REFERENCES tb_metric(ID),
    FOREIGN KEY (fin) REFERENCES tb_metric(ID),
    FOREIGN KEY (fout) REFERENCES tb_metric(ID),
    FOREIGN KEY (iovars) REFERENCES tb_metric(ID),
    FOREIGN KEY (mclc) REFERENCES tb_metric(ID),
    FOREIGN KEY (nbd) REFERENCES tb_metric(ID),
    FOREIGN KEY (ncomp) REFERENCES tb_metric(ID),
    FOREIGN KEY (nop) REFERENCES tb_metric(ID),
    FOREIGN KEY (nvar) REFERENCES tb_metric(ID),
    FOREIGN KEY (si) REFERENCES tb_metric(ID),
    FOREIGN KEY (tloc) REFERENCES tb_metric(ID),
    FOREIGN KEY (vg) REFERENCES tb_metric(ID),
    FOREIGN KEY (classID) REFERENCES tb_classMetrics(ID)
);
